from .datang_group_switch import (
    NODE_CLASS_MAPPINGS as GROUP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GROUP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .datang_group_presence import (
    NODE_CLASS_MAPPINGS as GROUP_PRESENCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GROUP_PRESENCE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .datang_boolean_nand import (
    NODE_CLASS_MAPPINGS as BOOLEAN_NAND_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_NAND_NODE_DISPLAY_NAME_MAPPINGS,
)
from .datang_lazy_switch import (
    NODE_CLASS_MAPPINGS as LAZY_SWITCH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LAZY_SWITCH_NODE_DISPLAY_NAME_MAPPINGS,
)
from .prompt_switchboard import (
    NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .model_selector import (
    NODE_CLASS_MAPPINGS as MODEL_SELECTOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MODEL_SELECTOR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .relighting_prompt import (
    NODE_CLASS_MAPPINGS as RELIGHTING_PROMPT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RELIGHTING_PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .id_photo_layout import (
    NODE_CLASS_MAPPINGS as ID_PHOTO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ID_PHOTO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .portrait_composition import (
    NODE_CLASS_MAPPINGS as PORTRAIT_COMPOSITION_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PORTRAIT_COMPOSITION_NODE_DISPLAY_NAME_MAPPINGS,
)
from .id_photo_quick_crop import (
    NODE_CLASS_MAPPINGS as ID_PHOTO_QUICK_CROP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ID_PHOTO_QUICK_CROP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .id_photo_ratio_crop import (
    NODE_CLASS_MAPPINGS as ID_PHOTO_RATIO_CROP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ID_PHOTO_RATIO_CROP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_size_restore import (
    NODE_CLASS_MAPPINGS as IMAGE_SIZE_RESTORE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_SIZE_RESTORE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .aspect_crop import (
    NODE_CLASS_MAPPINGS as ASPECT_CROP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ASPECT_CROP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .photo_print_crop import (
    NODE_CLASS_MAPPINGS as PHOTO_PRINT_CROP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PHOTO_PRINT_CROP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .id_photo_dpi_save import (
    NODE_CLASS_MAPPINGS as ID_PHOTO_DPI_SAVE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as ID_PHOTO_DPI_SAVE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .stage_result_save import (
    NODE_CLASS_MAPPINGS as STAGE_RESULT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as STAGE_RESULT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .fast_face_beauty import (
    NODE_CLASS_MAPPINGS as FACE_BEAUTY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FACE_BEAUTY_NODE_DISPLAY_NAME_MAPPINGS,
)
from .blemish_retouch import (
    NODE_CLASS_MAPPINGS as BLEMISH_RETOUCH_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BLEMISH_RETOUCH_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **RELIGHTING_PROMPT_NODE_CLASS_MAPPINGS,
    **PROMPT_NODE_CLASS_MAPPINGS,
    **GROUP_NODE_CLASS_MAPPINGS,
    **GROUP_PRESENCE_NODE_CLASS_MAPPINGS,
    **BOOLEAN_NAND_NODE_CLASS_MAPPINGS,
    **LAZY_SWITCH_NODE_CLASS_MAPPINGS,
    **MODEL_SELECTOR_NODE_CLASS_MAPPINGS,
    **PORTRAIT_COMPOSITION_NODE_CLASS_MAPPINGS,
    **ID_PHOTO_QUICK_CROP_NODE_CLASS_MAPPINGS,
    **ID_PHOTO_RATIO_CROP_NODE_CLASS_MAPPINGS,
    **IMAGE_SIZE_RESTORE_NODE_CLASS_MAPPINGS,
    **ASPECT_CROP_NODE_CLASS_MAPPINGS,
    **PHOTO_PRINT_CROP_NODE_CLASS_MAPPINGS,
    **ID_PHOTO_NODE_CLASS_MAPPINGS,
    **ID_PHOTO_DPI_SAVE_NODE_CLASS_MAPPINGS,
    **STAGE_RESULT_NODE_CLASS_MAPPINGS,
    **FACE_BEAUTY_NODE_CLASS_MAPPINGS,
    **BLEMISH_RETOUCH_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **RELIGHTING_PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,
    **GROUP_NODE_DISPLAY_NAME_MAPPINGS,
    **GROUP_PRESENCE_NODE_DISPLAY_NAME_MAPPINGS,
    **BOOLEAN_NAND_NODE_DISPLAY_NAME_MAPPINGS,
    **LAZY_SWITCH_NODE_DISPLAY_NAME_MAPPINGS,
    **MODEL_SELECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **PORTRAIT_COMPOSITION_NODE_DISPLAY_NAME_MAPPINGS,
    **ID_PHOTO_QUICK_CROP_NODE_DISPLAY_NAME_MAPPINGS,
    **ID_PHOTO_RATIO_CROP_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_SIZE_RESTORE_NODE_DISPLAY_NAME_MAPPINGS,
    **ASPECT_CROP_NODE_DISPLAY_NAME_MAPPINGS,
    **PHOTO_PRINT_CROP_NODE_DISPLAY_NAME_MAPPINGS,
    **ID_PHOTO_NODE_DISPLAY_NAME_MAPPINGS,
    **ID_PHOTO_DPI_SAVE_NODE_DISPLAY_NAME_MAPPINGS,
    **STAGE_RESULT_NODE_DISPLAY_NAME_MAPPINGS,
    **FACE_BEAUTY_NODE_DISPLAY_NAME_MAPPINGS,
    **BLEMISH_RETOUCH_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"
__version__ = "0.4.57"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
    "__version__",
]
